spring:
  application.name: api-gateway
  sleuth:
    sampler:
      percentage: 1.0
security.basic.enabled: false
management.security.enabled: false
info.foo: bar
info.app.encoding: @project.build.sourceEncoding@
info.app.java.source: @java.version@
info.app.java.target: @java.version@
server.port: 9000

zuul:
  ignoredServices: '*'
  routes:
    address-book-service: /service/**
    address-book-client: /client/**






